### ISSUE TITLE
Invert _Base64Lenient?

### ISSUE THREAD

**Issue by amesgen** [emilypi/base64-lens#1]
Thanks for this nice utility package! I found the following behavior to be surprising:
```haskell
 Λ _Base64 # "Zm9v"
"Wm05dg==" 
 Λ _Base64Lenient # "Zm9v"
"foo"
```
Of course this is a very minor thing, but it could be rather annoying during refactoring as the types don't help here.

---

In contrast, we have
```haskell
 Λ Base64 "Zm9v"
"Wm05dg==" 
 Λ Base64Lenient "Zm9v"
"Wm05dg=="
```
for patterns.

**Comment by emilypi** [comment]
These are swapped in the case of the optic so that `from` and `to` are more idiomatic when you use it as a `Lens`. I.e. 

```haskell
П> "U3Vu" ^. from _Base64Lenient
"Sun"

-- and 

П> "Sun" ^. to _Base64Lenient
"U3Vu"
```

Unfortunately, the `Prism` and `Lens` interpretation are at odds here w.r.t `Iso` - they are swapped - so we do have to choose which one will be "better". When used, one of the `Prism` or the `Lens` interpretation of the optic will be backwards, and since the encode/lenient decode pairs are primarily lenslike, I went with that. The question for me now is whether the dissonance is worth paying the price of admission for being symmetric with other `Prism`s, since `from _Base64Lenient` would then imply "encoding" and `to ...`, decoding. That's a little weird! You're not the only one that finds this bad - I do agree that `Prism`s and `Iso`s should align and `Iso` should be thought of as a more general `Prism`: https://github.com/ekmett/lens/issues/821

However, the pattern for `Base64Lenient` should work exactly as you'd expect - a constructed pattern encodes, and a destructed pattern decodes: 

```haskell
П> Base64Lenient "Sun"
"U3Vu"
П> case "U3Vu" of Base64Lenient a -> a 
"Sun"
```

I'll need to think about this. I do agree with Ed here, but breaking with convention would require a major version bump. Let's keep this one open for a bit and I'll decide what to do (most likely swap them for all libraries)

**Comment by amesgen** [comment]
Thanks for your quick response!

Yeah, it is confusing that the arguments of `iso` and `prism'` are "swapped". Like you, I also consider the symmetry between `_Base64` and `_Base64Lenient` to be more important than `from _Base64Lenient` being decoding:

 - We can't "swap" `_Base64`, as it is a prism.
 - A priori, it is unclear what "direction" `_Base64Lenient` has (encoding or decoding), but for some reason, we have a strong intuition for `from _Base64Lenient`, which is weird. This could be fixed by renaming it to `_Base64Lenient{Encoding,Decoding}`.
 - One can argue that `from` is actually not the "right" name for Iso reversal in general.

Small typo: You wrote `"Sun" ^. to _Base64Lenient`, the `to` does not work there.

As I mentioned above, the patterns behave like I would expect, in contrast to `_Base64` vs `_Base64Lenient`.

**Comment by emilypi** [comment]
> One can argue that from is actually not the "right" name for Iso reversal in general.

I buy this argument. I'm willing to start setting the convention that `Iso`'s should skew towards `Prism` and that `from` is just plain wrong 😄

> Small typo: You wrote "Sun" ^. to _Base64Lenient, the to does not work there.

Yes, sorry. Remove the `to` and it's fixed. 

Alright, no one depends on this library yet. I'll push out a new major version and just bite the bullet now while the project is young.

**Comment by emilypi** [comment]
Done! Thank you for raising this. The latest release, `0.3`, has the inverted `Iso`'s. I'll remember to do this on `base32-lens` as well, when I finish the lenient decoder.
